name: 'Github Actions Weather Bot'

on: 
  push:
  schedule:
    - cron: '0 14 * * *'

jobs: 
  bot:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - name: 'Install node'
      uses: actions/setup-node@v2
    - name: 'Install NPM dependencies'
      run: npm install
    - name: 'Run code'
      run: node index.js
      env: 
      TELEGRAM_API: ${{ secrets.TELEGRAM_API}}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      WEATHER_API: ${{ secrets.WEATHER_API }}
